version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  todo:
    lang: golang-middleware
    handler: ./todo
    image: ${REGISTRY:-ttl.sh}/${OWNER:-openfaas-function}/todo:${TAG:-latest}
    environment:
      STORE: memory
      VERSION: ${VERSION:-dev}
    # secrets:
    #   - todo-db-url
configuration:
  copy:
    - static
  templates:
    - name: golang-middleware
      source: https://github.com/openfaas/golang-http-template#0.9.1
